# city_mapping.py
# 常见城市英文名到中文名的映射

city_mapping = {
    # === 中国直辖市 ===
    'Beijing': '北京',
    'Shanghai': '上海',
    'Tianjin': '天津',
    'Chongqing': '重庆',
    
    # === 河北省 ===
    'Shijiazhuang': '石家庄',
    'Tangshan': '唐山',
    'Qinhuangdao': '秦皇岛',
    'Handan': '邯郸',
    'Xingtai': '邢台',
    'Baoding': '保定',
    'Zhangjiakou': '张家口',
    'Chengde': '承德',
    'Cangzhou': '沧州',
    'Langfang': '廊坊',
    'Hengshui': '衡水',
    
    # === 山西省 ===
    'Taiyuan': '太原',
    'Datong': '大同',
    'Yangquan': '阳泉',
    'Changzhi': '长治',
    'Jincheng': '晋城',
    'Shuozhou': '朔州',
    'Jinzhong': '晋中',
    'Yuncheng': '运城',
    'Xinzhou': '忻州',
    'Linfen': '临汾',
    'Lvliang': '吕梁',
    
    # === 内蒙古自治区 ===
    'Hohhot': '呼和浩特',
    'Baotou': '包头',
    'Wuhai': '乌海',
    'Chifeng': '赤峰',
    'Tongliao': '通辽',
    'Ordos': '鄂尔多斯',
    'Hulunbuir': '呼伦贝尔',
    'Bayannur': '巴彦淖尔',
    'Ulanqab': '乌兰察布',
    
    # === 辽宁省 ===
    'Shenyang': '沈阳',
    'Dalian': '大连',
    'Anshan': '鞍山',
    'Fushun': '抚顺',
    'Benxi': '本溪',
    'Dandong': '丹东',
    'Jinzhou': '锦州',
    'Yingkou': '营口',
    'Fuxin': '阜新',
    'Liaoyang': '辽阳',
    'Panjin': '盘锦',
    'Tieling': '铁岭',
    'Chaoyang': '朝阳',
    'Huludao': '葫芦岛',
    
    # === 吉林省 ===
    'Changchun': '长春',
    'Jilin': '吉林',
    'Siping': '四平',
    'Liaoyuan': '辽源',
    'Tonghua': '通化',
    'Baishan': '白山',
    'Songyuan': '松原',
    'Baicheng': '白城',
    'Yanji': '延吉',
    
    # === 黑龙江省 ===
    'Harbin': '哈尔滨',
    'Qiqihar': '齐齐哈尔',
    'Jixi': '鸡西',
    'Hegang': '鹤岗',
    'Shuangyashan': '双鸭山',
    'Daqing': '大庆',
    'Yichun': '伊春',
    'Jiamusi': '佳木斯',
    'Qitaihe': '七台河',
    'Mudanjiang': '牡丹江',
    'Heihe': '黑河',
    'Suihua': '绥化',
    
    # === 江苏省 ===
    'Nanjing': '南京',
    'Suzhou': '苏州',
    'Wuxi': '无锡',
    'Changzhou': '常州',
    'Zhenjiang': '镇江',
    'Nantong': '南通',
    'Taizhou': '泰州',
    'Yangzhou': '扬州',
    'Xuzhou': '徐州',
    'Huai\'an': '淮安',
    'Huaian': '淮安',
    'Suqian': '宿迁',
    'Lianyungang': '连云港',
    'Yancheng': '盐城',
    
    # === 浙江省 ===
    'Hangzhou': '杭州',
    'Ningbo': '宁波',
    'Wenzhou': '温州',
    'Jiaxing': '嘉兴',
    'Huzhou': '湖州',
    'Shaoxing': '绍兴',
    'Jinhua': '金华',
    'Quzhou': '衢州',
    'Zhoushan': '舟山',
    'Taizhou': '台州',
    'Lishui': '丽水',
    
    # === 安徽省 ===
    'Hefei': '合肥',
    'Wuhu': '芜湖',
    'Bengbu': '蚌埠',
    'Huainan': '淮南',
    'Ma\'anshan': '马鞍山',
    'Maanshan': '马鞍山',
    'Huaibei': '淮北',
    'Tongling': '铜陵',
    'Anqing': '安庆',
    'Huangshan': '黄山',
    'Chuzhou': '滁州',
    'Fuyang': '阜阳',
    'Suzhou': '宿州',
    'Lu\'an': '六安',
    'Luan': '六安',
    'Bozhou': '亳州',
    'Chizhou': '池州',
    'Xuancheng': '宣城',
    
    # === 福建省 ===
    'Fuzhou': '福州',
    'Xiamen': '厦门',
    'Putian': '莆田',
    'Sanming': '三明',
    'Quanzhou': '泉州',
    'Zhangzhou': '漳州',
    'Nanping': '南平',
    'Longyan': '龙岩',
    'Ningde': '宁德',
    
    # === 江西省 ===
    'Nanchang': '南昌',
    'Jingdezhen': '景德镇',
    'Pingxiang': '萍乡',
    'Jiujiang': '九江',
    'Xinyu': '新余',
    'Yingtan': '鹰潭',
    'Ganzhou': '赣州',
    'Ji\'an': '吉安',
    'Jian': '吉安',
    'Yichun': '宜春',
    'Fuzhou': '抚州',
    'Shangrao': '上饶',
    
    # === 山东省 ===
    'Jinan': '济南',
    'Qingdao': '青岛',
    'Zibo': '淄博',
    'Zaozhuang': '枣庄',
    'Dongying': '东营',
    'Yantai': '烟台',
    'Weifang': '潍坊',
    'Jining': '济宁',
    'Tai\'an': '泰安',
    'Taian': '泰安',
    'Weihai': '威海',
    'Rizhao': '日照',
    'Linyi': '临沂',
    'Dezhou': '德州',
    'Liaocheng': '聊城',
    'Binzhou': '滨州',
    'Heze': '菏泽',
    
    # === 河南省 ===
    'Zhengzhou': '郑州',
    'Kaifeng': '开封',
    'Luoyang': '洛阳',
    'Pingdingshan': '平顶山',
    'Anyang': '安阳',
    'Hebi': '鹤壁',
    'Xinxiang': '新乡',
    'Jiaozuo': '焦作',
    'Puyang': '濮阳',
    'Xuchang': '许昌',
    'Luohe': '漯河',
    'Sanmenxia': '三门峡',
    'Nanyang': '南阳',
    'Shangqiu': '商丘',
    'Xinyang': '信阳',
    'Zhoukou': '周口',
    'Zhumadian': '驻马店',
    
    # === 湖北省 ===
    'Wuhan': '武汉',
    'Huangshi': '黄石',
    'Shiyan': '十堰',
    'Yichang': '宜昌',
    'Xiangyang': '襄阳',
    'Ezhou': '鄂州',
    'Jingmen': '荆门',
    'Xiaogan': '孝感',
    'Jingzhou': '荆州',
    'Huanggang': '黄冈',
    'Xianning': '咸宁',
    'Suizhou': '随州',
    
    # === 湖南省 ===
    'Changsha': '长沙',
    'Zhuzhou': '株洲',
    'Xiangtan': '湘潭',
    'Hengyang': '衡阳',
    'Shaoyang': '邵阳',
    'Yueyang': '岳阳',
    'Changde': '常德',
    'Zhangjiajie': '张家界',
    'Yiyang': '益阳',
    'Chenzhou': '郴州',
    'Yongzhou': '永州',
    'Huaihua': '怀化',
    'Loudi': '娄底',
    
    # === 广东省 ===
    'Guangzhou': '广州',
    'Shenzhen': '深圳',
    'Zhuhai': '珠海',
    'Shantou': '汕头',
    'Foshan': '佛山',
    'Shaoguan': '韶关',
    'Zhanjiang': '湛江',
    'Zhaoqing': '肇庆',
    'Jiangmen': '江门',
    'Maoming': '茂名',
    'Huizhou': '惠州',
    'Meizhou': '梅州',
    'Shanwei': '汕尾',
    'Heyuan': '河源',
    'Yangjiang': '阳江',
    'Qingyuan': '清远',
    'Dongguan': '东莞',
    'Zhongshan': '中山',
    'Chaozhou': '潮州',
    'Jieyang': '揭阳',
    'Yunfu': '云浮',
    
    # === 广西壮族自治区 ===
    'Nanning': '南宁',
    'Liuzhou': '柳州',
    'Guilin': '桂林',
    'Wuzhou': '梧州',
    'Beihai': '北海',
    'Fangchenggang': '防城港',
    'Qinzhou': '钦州',
    'Guigang': '贵港',
    'Yulin': '玉林',
    'Baise': '百色',
    'Hezhou': '贺州',
    'Hechi': '河池',
    'Laibin': '来宾',
    'Chongzuo': '崇左',
    
    # === 海南省 ===
    'Haikou': '海口',
    'Sanya': '三亚',
    'Sansha': '三沙',
    'Danzhou': '儋州',
    
    # === 四川省 ===
    'Chengdu': '成都',
    'Zigong': '自贡',
    'Panzhihua': '攀枝花',
    'Luzhou': '泸州',
    'Deyang': '德阳',
    'Mianyang': '绵阳',
    'Guangyuan': '广元',
    'Suining': '遂宁',
    'Neijiang': '内江',
    'Leshan': '乐山',
    'Nanchong': '南充',
    'Meishan': '眉山',
    'Yibin': '宜宾',
    'Guang\'an': '广安',
    'Guangan': '广安',
    'Dazhou': '达州',
    'Ya\'an': '雅安',
    'Yaan': '雅安',
    'Bazhong': '巴中',
    'Ziyang': '资阳',
    
    # === 贵州省 ===
    'Guiyang': '贵阳',
    'Liupanshui': '六盘水',
    'Zunyi': '遵义',
    'Anshun': '安顺',
    'Bijie': '毕节',
    'Tongren': '铜仁',
    
    # === 云南省 ===
    'Kunming': '昆明',
    'Qujing': '曲靖',
    'Yuxi': '玉溪',
    'Baoshan': '保山',
    'Zhaotong': '昭通',
    'Lijiang': '丽江',
    'Pu\'er': '普洱',
    'Puer': '普洱',
    'Lincang': '临沧',
    
    # === 西藏自治区 ===
    'Lhasa': '拉萨',
    'Shigatse': '日喀则',
    'Qamdo': '昌都',
    'Nyingchi': '林芝',
    'Shannan': '山南',
    'Nagqu': '那曲',
    
    # === 陕西省 ===
    'Xi\'an': '西安',
    'Xian': '西安',
    'Tongchuan': '铜川',
    'Baoji': '宝鸡',
    'Xianyang': '咸阳',
    'Weinan': '渭南',
    'Yan\'an': '延安',
    'Yanan': '延安',
    'Hanzhong': '汉中',
    'Yulin': '榆林',
    'Ankang': '安康',
    'Shangluo': '商洛',
    
    # === 甘肃省 ===
    'Lanzhou': '兰州',
    'Jiayuguan': '嘉峪关',
    'Jinchang': '金昌',
    'Baiyin': '白银',
    'Tianshui': '天水',
    'Wuwei': '武威',
    'Zhangye': '张掖',
    'Pingliang': '平凉',
    'Jiuquan': '酒泉',
    'Qingyang': '庆阳',
    'Dingxi': '定西',
    'Longnan': '陇南',
    
    # === 青海省 ===
    'Xining': '西宁',
    'Haidong': '海东',
    
    # === 宁夏回族自治区 ===
    'Yinchuan': '银川',
    'Shizuishan': '石嘴山',
    'Wuzhong': '吴忠',
    'Guyuan': '固原',
    'Zhongwei': '中卫',
    
    # === 新疆维吾尔自治区 ===
    'Urumqi': '乌鲁木齐',
    'Karamay': '克拉玛依',
    'Turpan': '吐鲁番',
    'Hami': '哈密',
    'Changji': '昌吉',
    'Bortala': '博尔塔拉',
    'Bayingolin': '巴音郭楞',
    'Aksu': '阿克苏',
    'Kizilsu': '克孜勒苏',
    'Kashgar': '喀什',
    'Hotan': '和田',
    'Ili': '伊犁',
    'Tacheng': '塔城',
    'Altay': '阿勒泰',
    
    # === 港澳台 ===
    'Hong Kong': '香港',
    'Kowloon': '九龙',
    'Macau': '澳门',
    'Macao': '澳门',
    'Taipei': '台北',
    'Kaohsiung': '高雄',
    'Taichung': '台中',
    'Tainan': '台南',
    'Keelung': '基隆',
    'Hsinchu': '新竹',
    'Chiayi': '嘉义',
    'Taoyuan': '桃园',
    
    # === 美国主要城市 ===
    'New York': '纽约',
    'Los Angeles': '洛杉矶',
    'Chicago': '芝加哥',
    'Houston': '休斯顿',
    'Phoenix': '凤凰城',
    'Philadelphia': '费城',
    'San Antonio': '圣安东尼奥',
    'San Diego': '圣地亚哥',
    'Dallas': '达拉斯',
    'San Jose': '圣何塞',
    'Austin': '奥斯汀',
    'Jacksonville': '杰克逊维尔',
    'San Francisco': '旧金山',
    'Columbus': '哥伦布',
    'Fort Worth': '沃斯堡',
    'Indianapolis': '印第安纳波利斯',
    'Charlotte': '夏洛特',
    'Seattle': '西雅图',
    'Denver': '丹佛',
    'Washington': '华盛顿',
    'Boston': '波士顿',
    'Nashville': '纳什维尔',
    'Detroit': '底特律',
    'Portland': '波特兰',
    'Las Vegas': '拉斯维加斯',
    'Miami': '迈阿密',
    'Atlanta': '亚特兰大',
    'Minneapolis': '明尼阿波利斯',
    'Tampa': '坦帕',
    'Cleveland': '克利夫兰',
    'Pittsburgh': '匹兹堡',
    'Orlando': '奥兰多',
    'Sacramento': '萨克拉门托',
    'Kansas City': '堪萨斯城',
    'St. Louis': '圣路易斯',
    'Salt Lake City': '盐湖城',
    'Ashburn': '阿什本',
    'Mountain View': '山景城',
    'Palo Alto': '帕洛阿尔托',
    'Santa Clara': '圣克拉拉',
    'Fremont': '弗里蒙特',
    'Sunnyvale': '森尼韦尔',
    'East Palo Alto': '东帕洛阿尔托',
    'Cupertino': '库比蒂诺',
    'Redwood City': '红木城',
    'Menlo Park': '门洛帕克',
    'San Mateo': '圣马特奥',
    'Berkeley': '伯克利',
    'Oakland': '奥克兰',
    'Pasadena': '帕萨迪纳',
    'Long Beach': '长滩',
    'Anaheim': '阿纳海姆',
    'Riverside': '里弗赛德',
    'Santa Barbara': '圣巴巴拉',
    'Irvine': '尔湾',
    'San Bernardino': '圣贝纳迪诺',
    'Fresno': '弗雷斯诺',
    'Bakersfield': '贝克斯菲尔德',
    'Stockton': '斯托克顿',
    'Modesto': '莫德斯托',
    'Reno': '里诺',
    'Tucson': '图森',
    'Albuquerque': '阿尔伯克基',
    'El Paso': '埃尔帕索',
    'Oklahoma City': '俄克拉何马城',
    'Memphis': '孟菲斯',
    'Louisville': '路易斯维尔',
    'Baltimore': '巴尔的摩',
    'Milwaukee': '密尔沃基',
    'Raleigh': '罗利',
    'Richmond': '里士满',
    'New Orleans': '新奥尔良',
    'Buffalo': '布法罗',
    'Rochester': '罗切斯特',
    'Omaha': '奥马哈',
    'Des Moines': '得梅因',
    'Wichita': '威奇托',
    'Tulsa': '塔尔萨',
    'Spokane': '斯波坎',
    'Boise': '博伊西',
    'Anchorage': '安克雷奇',
    'Honolulu': '火奴鲁鲁',
    
    # === 欧洲主要城市 ===
    'London': '伦敦',
    'Paris': '巴黎',
    'Berlin': '柏林',
    'Madrid': '马德里',
    'Rome': '罗马',
    'Amsterdam': '阿姆斯特丹',
    'Vienna': '维也纳',
    'Brussels': '布鲁塞尔',
    'Stockholm': '斯德哥尔摩',
    'Copenhagen': '哥本哈根',
    'Oslo': '奥斯陆',
    'Helsinki': '赫尔辛基',
    'Dublin': '都柏林',
    'Lisbon': '里斯本',
    'Warsaw': '华沙',
    'Prague': '布拉格',
    'Budapest': '布达佩斯',
    'Athens': '雅典',
    'Zurich': '苏黎世',
    'Geneva': '日内瓦',
    'Frankfurt': '法兰克福',
    'Munich': '慕尼黑',
    'Hamburg': '汉堡',
    'Cologne': '科隆',
    'Stuttgart': '斯图加特',
    'Dusseldorf': '杜塞尔多夫',
    'Düsseldorf': '杜塞尔多夫',
    'Dortmund': '多特蒙德',
    'Essen': '埃森',
    'Leipzig': '莱比锡',
    'Dresden': '德累斯顿',
    'Hanover': '汉诺威',
    'Nuremberg': '纽伦堡',
    'Barcelona': '巴塞罗那',
    'Valencia': '巴伦西亚',
    'Seville': '塞维利亚',
    'Zaragoza': '萨拉戈萨',
    'Málaga': '马拉加',
    'Malaga': '马拉加',
    'Bilbao': '毕尔巴鄂',
    'Milan': '米兰',
    'Naples': '那不勒斯',
    'Turin': '都灵',
    'Florence': '佛罗伦萨',
    'Venice': '威尼斯',
    'Bologna': '博洛尼亚',
    'Genoa': '热那亚',
    'Moscow': '莫斯科',
    'St Petersburg': '圣彼得堡',
    'Saint Petersburg': '圣彼得堡',
    'Novosibirsk': '新西伯利亚',
    'Yekaterinburg': '叶卡捷琳堡',
    'Kazan': '喀山',
    'Samara': '萨马拉',
    'Istanbul': '伊斯坦布尔',
    'Ankara': '安卡拉',
    'Izmir': '伊兹密尔',
    'Bucharest': '布加勒斯特',
    'Sofia': '索菲亚',
    'Belgrade': '贝尔格莱德',
    'Zagreb': '萨格勒布',
    'Ljubljana': '卢布尔雅那',
    'Bratislava': '布拉迪斯拉发',
    'Vilnius': '维尔纽斯',
    'Riga': '里加',
    'Tallinn': '塔林',
    'Reykjavik': '雷克雅未克',
    'Luxembourg': '卢森堡',
    'Monaco': '摩纳哥',
    'Andorra': '安道尔',
    'Valletta': '瓦莱塔',
    'Nicosia': '尼科西亚',
    'Manchester': '曼彻斯特',
    'Birmingham': '伯明翰',
    'Glasgow': '格拉斯哥',
    'Liverpool': '利物浦',
    'Edinburgh': '爱丁堡',
    'Leeds': '利兹',
    'Sheffield': '谢菲尔德',
    'Bristol': '布里斯托',
    'Cardiff': '卡迪夫',
    'Belfast': '贝尔法斯特',
    
    # === 亚洲主要城市 ===
    'Tokyo': '东京',
    'Osaka': '大阪',
    'Kyoto': '京都',
    'Yokohama': '横滨',
    'Nagoya': '名古屋',
    'Sapporo': '札幌',
    'Kobe': '神户',
    'Fukuoka': '福冈',
    'Kawasaki': '川崎',
    'Saitama': '埼玉',
    'Hiroshima': '广岛',
    'Sendai': '仙台',
    'Kitakyushu': '北九州',
    'Chiba': '千叶',
    'Seoul': '首尔',
    'Busan': '釜山',
    'Incheon': '仁川',
    'Daegu': '大邱',
    'Daejeon': '大田',
    'Gwangju': '光州',
    'Ulsan': '蔚山',
    'Suwon': '水原',
    'Bangkok': '曼谷',
    'Singapore': '新加坡',
    'Kuala Lumpur': '吉隆坡',
    'Penang': '槟城',
    'Johor Bahru': '新山',
    'George Town': '乔治市',
    'Ipoh': '怡保',
    'Jakarta': '雅加达',
    'Surabaya': '泗水',
    'Bandung': '万隆',
    'Medan': '棉兰',
    'Semarang': '三宝垄',
    'Makassar': '望加锡',
    'Manila': '马尼拉',
    'Quezon City': '奎松市',
    'Davao': '达沃',
    'Cebu': '宿务',
    'Hanoi': '河内',
    'Ho Chi Minh City': '胡志明市',
    'Hai Phong': '海防',
    'Da Nang': '岘港',
    'Can Tho': '芹苴',
    'Mumbai': '孟买',
    'Delhi': '德里',
    'New Delhi': '新德里',
    'Bangalore': '班加罗尔',
    'Hyderabad': '海得拉巴',
    'Chennai': '金奈',
    'Kolkata': '加尔各答',
    'Pune': '浦那',
    'Ahmedabad': '艾哈迈达巴德',
    'Jaipur': '斋浦尔',
    'Lucknow': '勒克瑙',
    'Kanpur': '坎普尔',
    'Nagpur': '那格浦尔',
    'Indore': '印多尔',
    'Thane': '塔那',
    'Bhopal': '博帕尔',
    'Visakhapatnam': '维沙卡帕特南',
    'Karachi': '卡拉奇',
    'Lahore': '拉合尔',
    'Islamabad': '伊斯兰堡',
    'Dhaka': '达卡',
    'Chittagong': '吉大港',
    'Colombo': '科伦坡',
    'Kathmandu': '加德满都',
    'Yangon': '仰光',
    'Mandalay': '曼德勒',
    'Phnom Penh': '金边',
    'Vientiane': '万象',
    'Dubai': '迪拜',
    'Abu Dhabi': '阿布扎比',
    'Sharjah': '沙迦',
    'Doha': '多哈',
    'Riyadh': '利雅得',
    'Jeddah': '吉达',
    'Mecca': '麦加',
    'Medina': '麦地那',
    'Dammam': '达曼',
    'Kuwait City': '科威特城',
    'Manama': '麦纳麦',
    'Muscat': '马斯喀特',
    'Amman': '安曼',
    'Beirut': '贝鲁特',
    'Damascus': '大马士革',
    'Baghdad': '巴格达',
    'Tehran': '德黑兰',
    'Tel Aviv': '特拉维夫',
    'Jerusalem': '耶路撒冷',
    'Haifa': '海法',
    
    # === 大洋洲主要城市 ===
    'Sydney': '悉尼',
    'Melbourne': '墨尔本',
    'Brisbane': '布里斯班',
    'Perth': '珀斯',
    'Adelaide': '阿德莱德',
    'Gold Coast': '黄金海岸',
    'Canberra': '堪培拉',
    'Newcastle': '纽卡斯尔',
    'Wollongong': '卧龙岗',
    'Hobart': '霍巴特',
    'Geelong': '吉朗',
    'Townsville': '汤斯维尔',
    'Cairns': '凯恩斯',
    'Darwin': '达尔文',
    'Auckland': '奥克兰',
    'Wellington': '惠灵顿',
    'Christchurch': '基督城',
    'Hamilton': '汉密尔顿',
    'Tauranga': '陶兰加',
    'Dunedin': '但尼丁',
    'Suva': '苏瓦',
    'Port Moresby': '莫尔兹比港',
    
    # === 北美其他城市 ===
    'Toronto': '多伦多',
    'Montreal': '蒙特利尔',
    'Vancouver': '温哥华',
    'Calgary': '卡尔加里',
    'Ottawa': '渥太华',
    'Edmonton': '埃德蒙顿',
    'Mississauga': '密西沙加',
    'Winnipeg': '温尼伯',
    'Quebec City': '魁北克城',
    'Hamilton': '哈密尔顿',
    'Kitchener': '基奇纳',
    'London': '伦敦',
    'Victoria': '维多利亚',
    'Halifax': '哈利法克斯',
    'Mexico City': '墨西哥城',
    'Guadalajara': '瓜达拉哈拉',
    'Monterrey': '蒙特雷',
    'Puebla': '普埃布拉',
    'Tijuana': '蒂华纳',
    'León': '莱昂',
    'Leon': '莱昂',
    'Juárez': '华雷斯',
    'Juarez': '华雷斯',
    'Zapopan': '萨波潘',
    'Cancún': '坎昆',
    'Cancun': '坎昆',
    'Havana': '哈瓦那',
    'Kingston': '金斯敦',
    'Santo Domingo': '圣多明各',
    'San Juan': '圣胡安',
    'Nassau': '拿骚',
    'Port-au-Prince': '太子港',
    'Panama City': '巴拿马城',
    'San José': '圣何塞',
    'San Jose': '圣何塞',
    'Guatemala City': '危地马拉城',
    'Managua': '马那瓜',
    'San Salvador': '圣萨尔瓦多',
    'Tegucigalpa': '特古西加尔巴',
    'Belmopan': '贝尔莫潘',
    
    # === 南美主要城市 ===
    'Buenos Aires': '布宜诺斯艾利斯',
    'Córdoba': '科尔多瓦',
    'Cordoba': '科尔多瓦',
    'Rosario': '罗萨里奥',
    'Mendoza': '门多萨',
    'São Paulo': '圣保罗',
    'Sao Paulo': '圣保罗',
    'Rio de Janeiro': '里约热内卢',
    'Brasília': '巴西利亚',
    'Brasilia': '巴西利亚',
    'Salvador': '萨尔瓦多',
    'Fortaleza': '福塔莱萨',
    'Belo Horizonte': '贝洛奥里藏特',
    'Manaus': '马瑙斯',
    'Curitiba': '库里蒂巴',
    'Recife': '累西腓',
    'Porto Alegre': '阿雷格里港',
    'Santiago': '圣地亚哥',
    'Valparaíso': '瓦尔帕莱索',
    'Valparaiso': '瓦尔帕莱索',
    'Concepción': '康塞普西翁',
    'Concepcion': '康塞普西翁',
    'Lima': '利马',
    'Arequipa': '阿雷基帕',
    'Trujillo': '特鲁希略',
    'Bogotá': '波哥大',
    'Bogota': '波哥大',
    'Medellín': '麦德林',
    'Medellin': '麦德林',
    'Cali': '卡利',
    'Barranquilla': '巴兰基亚',
    'Cartagena': '卡塔赫纳',
    'Caracas': '加拉加斯',
    'Maracaibo': '马拉开波',
    'Valencia': '巴伦西亚',
    'Quito': '基多',
    'Guayaquil': '瓜亚基尔',
    'La Paz': '拉巴斯',
    'Santa Cruz': '圣克鲁斯',
    'Asunción': '亚松森',
    'Asuncion': '亚松森',
    'Montevideo': '蒙得维的亚',
    
    # === 非洲主要城市 ===
    'Cairo': '开罗',
    'Alexandria': '亚历山大',
    'Giza': '吉萨',
    'Lagos': '拉各斯',
    'Kano': '卡诺',
    'Ibadan': '伊巴丹',
    'Abuja': '阿布贾',
    'Port Harcourt': '哈科特港',
    'Johannesburg': '约翰内斯堡',
    'Cape Town': '开普敦',
    'Durban': '德班',
    'Pretoria': '比勒陀利亚',
    'Soweto': '索韦托',
    'Nairobi': '内罗毕',
    'Mombasa': '蒙巴萨',
    'Addis Ababa': '亚的斯亚贝巴',
    'Dar es Salaam': '达累斯萨拉姆',
    'Khartoum': '喀土穆',
    'Accra': '阿克拉',
    'Kinshasa': '金沙萨',
    'Luanda': '罗安达',
    'Kampala': '坎帕拉',
    'Dakar': '达喀尔',
    'Abidjan': '阿比让',
    'Casablanca': '卡萨布兰卡',
    'Rabat': '拉巴特',
    'Algiers': '阿尔及尔',
    'Tunis': '突尼斯',
    'Tripoli': '的黎波里',
    'Harare': '哈拉雷',
    'Lusaka': '卢萨卡',
    'Maputo': '马普托',
    'Antananarivo': '塔那那利佛',
}


def get_city_name(city_name):
    """
    根据英文城市名获取中文名称
    
    Args:
        city_name: 英文城市名
        
    Returns:
        中文城市名，如果未找到映射则返回原英文名
    """
    if not city_name:
        return city_name
    
    # 尝试精确匹配
    if city_name in city_mapping:
        return city_mapping[city_name]
    
    # 尝试不区分大小写匹配
    for eng_name, chn_name in city_mapping.items():
        if eng_name.lower() == city_name.lower():
            return chn_name
    
    # 如果没有找到映射，返回原名称
    return city_name


def get_location_display(country, city):
    """
    获取格式化的地理位置显示
    
    Args:
        country: 国家名（中文）
        city: 城市名（可能是英文或中文）
        
    Returns:
        格式化的位置字符串，如 "中国 北京" 或 "美国 纽约"
    """
    if not country and not city:
        return '-'
    
    city_cn = get_city_name(city) if city else ''
    
    if country and city_cn:
        return f"{country} {city_cn}"
    elif country:
        return country
    elif city_cn:
        return city_cn
    else:
        return '-'
