name: 部署 Flask 应用

on:
  push:
    branches:
      - main  # 当 main 分支有新的推送时触发工作流
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 设置权限，允许写入内容，例如创建 Release

    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: 设置 Python 环境
      uses: actions/setup-python@v3
      with:
        python-version: 3.9  # 指定 Python 版本为 3.9

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 安装 PyInstaller
      run: pip install pyinstaller

    - name: 打包 Flask 应用
      run: |
        cd $GITHUB_WORKSPACE/server  # 确保在包含 app.py 的目录下
        pyinstaller -F --hidden-import flask_cors --hidden-import requests --hidden-import dns.resolver --hidden-import country_mapping app.py
        ls -la dist  # 列出 dist 目录中的文件以确认生成的文件

    - name: 创建 Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: release-${{ github.sha }}
        release_name: Release ${{ github.sha }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GITHUB_TOKEN 进行身份验证

    - name: 上传打包容件到 Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: $GITHUB_WORKSPACE/server/dist/app  # 更新为正确的路径，例如 dist/app
        asset_name: app  # 确保这是生成的可执行文件的名称
        asset_content_type: application/octet-stream  # 设置文件内容类型
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GITHUB_TOKEN 进行身份验证

    - name: 上传打包文件为 artifact
      uses: actions/upload-artifact@v3
      with:
        name: ipinfo-flask-app
        path: $GITHUB_WORKSPACE/server/dist/app  # 确保路径正确
