name: 部署 Flask 应用

on:
  push:
    branches:
      - main  # 当 main 分支有新的推送时触发工作流
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 设置权限，允许写入内容，例如创建 Release

    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: 设置 Python 环境
      uses: actions/setup-python@v3
      with:
        python-version: 3.9  # 指定 Python 版本为 3.9

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 安装 PyInstaller
      run: pip install pyinstaller

    - name: 打包 Flask 应用
      run: |
        cd $GITHUB_WORKSPACE/server  # 确保在包含 app.py 的目录下
        pyinstaller -F --hidden-import flask_cors --hidden-import requests --hidden-import dns.resolver --hidden-import country_mapping app.py
        ls -la dist  # 列出 dist 目录中的文件以确认生成的文件

    - name: 检查可执行文件是否存在
      run: |
        if [ -f "$GITHUB_WORKSPACE/server/dist/app" ]; then
          echo "可执行文件存在，继续上传。"
        else
          echo "可执行文件不存在，请检查。"
          exit 1
        fi

    - name: 获取旧版号
      id: get_version
      run: |
        if [ -f version.txt ]; then
          version=$(cat version.txt)
        else
          version="version_0.1"  # 如果没有版本文件，则初始化版本号
        fi
        echo "当前版本号: $version"
        echo "version=$version" >> $GITHUB_ENV  # 设置环境变量

    - name: 更新版本号
      id: update_version
      run: |
        major=$(echo ${{ env.version }} | cut -d '_' -f 2)  # 获取当前版本号的主要部分
        # 提升版本号 
        new_major=$(echo "$major + 0.1" | bc)
        new_version="version_$new_major"
        echo $new_version > version.txt  # 将新版本写入文件
        echo "新的版本号: $new_version"
        echo "new_version=$new_version" >> $GITHUB_ENV  # 设置新的版本号为环境变量

    - name: 创建 Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.new_version }}  # 使用新的版本号作为 tag
        release_name: Release ${{ env.new_version }}  # 使用新的版本号作为 release 名称
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GITHUB_TOKEN 进行身份验证

    - name: 验证 dist 目录
      run: |
        echo "当前路径: $GITHUB_WORKSPACE/server/dist"
        ls -la $GITHUB_WORKSPACE/server/dist/

    - name: 上传打包容件到 Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/server/dist/app  # 使用环境变量
        asset_name: app_${{ env.new_version }}  # 使用新的版本号作为资产名称
        asset_content_type: application/octet-stream  # 设置文件内容类型
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GITHUB_TOKEN 进行身份验证

    - name: 上传打包文件为 artifact
      uses: actions/upload-artifact@v3
      with:
        name: ipinfo-flask-app_${{ env.new_version }}  # 使用新的版本号作为 artifact 名称
        path: ${{ github.workspace }}/server/dist/app
