name: Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pyinstaller
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Package the application with PyInstaller
        run: |
          pyinstaller --onefile --add-data "./server/.env:." "./server/app.py"
        env:
          IPINFO_TOKEN: ${{ secrets.IPINFO_TOKEN }}  # 确保设置了 IPINFO_TOKEN

      - name: Upload the packaged application
        uses: actions/upload-artifact@v3
        with:
          name: packaged-app
          path: server/dist/app  # 生成可执行文件的路径
